feat(input): add and test input component
takenet/blip-ds-react pull request #1
Opened 2023-01-03 12:10 UTC by lucasMurtaVI

2023-01-03 12:49 UTC, WillianLomeu requested changes

2023-01-03 12:49 UTC, WillianLomeu commented on src/components/input/event/bdsPatterValidation.js
> +      elementRef.addEventListener('bdsPatterValidation', (event) => {
Crie ou retorne algum exemplo em tela utilizando esse evento. No momento não está retornando nada.

2023-01-03 12:49 UTC, WillianLomeu commented on src/components/input/method/isValid.js
> +  const inputIsValid = async (id) => {
Crie algum retorno visual de que o método funciona. Pode seguir os exemplos de outros métodos e eventos.

2023-01-03 12:49 UTC, WillianLomeu commented on src/components/input/method/getInputElement.js
> +  const inputGetInputElement = async (id) => {
Crie algum retorno visual de que o método funciona. Pode seguir os exemplos de outros métodos e eventos.

2023-01-03 12:49 UTC, WillianLomeu commented on src/pages/componentList.js
> +          <Card name="Input Chips" status="success" statusText="Ok" />
mudou o card do input errado

2023-01-03 12:49 UTC, WillianLomeu commented on src/pages/componentList.js
> +          <Card name="Autocomplete" link="autocomplete" status="success" statusText="Ok" />
Mudou o status para ok, mas não foi feito nenhuma modificação no autocomplete.

2023-01-04 14:22 UTC, lucasMurtaVI commented on src/components/input/event/bdsPatterValidation.js
> +      elementRef.addEventListener('bdsPatterValidation', (event) => {
Will, esse patter validation eu não consegui fazer ele funcionar até peguei diretamente no código do input pra testar e não funcionou, adicionei o Input no nosso documento para manutenção dos componentes.

2023-01-05 14:11 UTC, WillianLomeu requested changes

2023-01-05 14:11 UTC, WillianLomeu commented on src/components/input/event/bdsPatterValidation.js
> +                <bds-input ref={elementRf} placeholder="nome completo" pattern="/^[0-9]*$/"></bds-input>
Qualquer alteração no código, deverá ser mostrado no código em tela.

2023-01-05 14:11 UTC, WillianLomeu commented on src/components/input/method/getInputElement.js
> +    input.value = inputElement;
O retorno está no value do input. É um retorno de muitos dados, pode fazer aquele card de outros exemplos aparecer e mostrar que o método foi chamado. Qualquer dúvida me chame no workchat.

2023-01-05 14:11 UTC, WillianLomeu commented on src/components/input/method/isValid.js
> +    input.value = validResult;
Retornando no próprio input, use o card dos outros exemplos para mostrar o valor de retorno.

2023-01-05 14:11 UTC, WillianLomeu commented on src/components/input/event/bdsPatterValidation.js
> +      elementRef.addEventListener('bdsPatterValidation', (event) => {
Coloque um banner informando que o método ou evento está com problema. Tem exemplo no autocomplete.

2023-01-05 14:15 UTC, lucasMurtaVI commented on src/components/input/event/bdsPatterValidation.js
> +                <bds-input ref={elementRf} placeholder="nome completo" pattern="/^[0-9]*$/"></bds-input>
Esse evento não esta funcionando direito, tem q rever como ele foi feito. coloquei o pattern ai pq la no componente tem uma função q emite o evento se o pattern estiver preenchido.

2023-01-05 21:52 UTC, WillianLomeu approved these changes

2023-01-06 12:21 UTC, merged